- name: install mysql client
  ansible.builtin.yum:
    name: mysql
    state: installed
    enabled: yes

- name: load schema
  ansible.builtin.shell: mysql -h mysql-dev.devops746.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql
