- name: download and install nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: pre-req setup
  ansible.builtin.import_tasks: app-pre-req.yml

- name: Install nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: setup-schema
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: setup-systemd
  ansible.builtin.import_tasks: systemd-setup.yml
